# Matriz de incidencia

In [37]:
# Modulos
import nltk 
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\gabri\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

## 1- Definir el stoplist

In [38]:
with open("stoplist.txt") as file:
    stoplist = [line.strip() for line in file]
stoplist += ['?', '-', '.', ':', ',']    

## 2-  Tokenizar y eliminar stopwords

In [39]:

list_docs = []
for i in range(1, 7):
    libro = f"libro{i}.txt"
    with open(libro) as file:
        doc = [line.strip() for line in file]
        list_docs.append(" ".join(doc)) 

for i, doc in enumerate(list_docs):
    tokens = nltk.word_tokenize(doc)  
    tokens = [word for word in tokens if word.lower() not in stoplist]  
    list_docs[i] = tokens  
    print(f"Libro {i+1}: {tokens}")  



Libro 1: ['obra', 'comienza', 'noticia', 'celebración', '111º', 'cumpleaños', 'Bilbo', 'Bolsón', 'Comarca', 'Bilbo', 'fiesta', 'tenÃ\xada', 'motivo', 'principal', 'partida', 'último', 'viaje', 'producto', 'deseo', 'terminar', 'dÃ\xadas', 'paz', 'tranquilidad', 'mago', 'Gandalf', 'amigo', 'Bilbo', 'informado', 'decisión', 'hobbit', 'también', 'acudió', 'fiesta', 'discurso', 'pronunciado', 'Bilbo', 'puso', 'anillo', 'mágico', 'desapareció', 'sorprendidos', 'hobbits', 'Gandalf', 'sabÃ\xada', 'acababa', 'Bilbo', 'encontró', 'Bolsón', 'Cerrado', 'allÃ\xad', 'pequeña', 'discusión', 'él', 'negaba', 'dejar', 'anillo', 'resto', 'herencia', 'sobrino', 'Frodo', ';', 'mago', 'acabó', 'convenciéndole', 'Bilbo', 'partió', 'dudas', 'ocasionando', 'anillo', 'Gandalf', 'busca', 'información', 'él', 'informar', 'Frodo', 'guarde', 'toque', 'veinte', 'años', 'después', 'Gandalf', 'regresa', 'Bolsón', 'Cerrado', 'Frodo', 'habÃ\xada', 'descubierto', 'Anillo', 'trataba', 'Rey', 'Isildu

## 3- Construir la matriz de incidencia

In [40]:
import numpy as np
def construir_matriz(list_docs):
    vocabulario = set()
    for doc in list_docs:
        vocabulario.update(doc)
    matriz = np.zeros((len(list_docs), len(vocabulario)), dtype=int)

    for i, doc in enumerate(list_docs):
        for palabra in doc:
            j = list(vocabulario).index(palabra)
            matriz[i][j] += 1
    
    return matriz, vocabulario
matriz_incidencia, vocabulario = construir_matriz(list_docs)
with open("matriz_incidencia.txt", "w") as file:
    file.write("\t".join(vocabulario) + "\n")
    
    for fila in matriz_incidencia:
        file.write("\t".join(map(str, fila)) + "\n")
        print(fila)
        print("\n")


[0 0 0 ... 1 0 0]


[2 0 0 ... 0 1 0]


[2 2 1 ... 0 0 1]


[0 0 0 ... 0 0 0]


[1 0 0 ... 0 0 0]


[0 0 0 ... 0 0 0]




## 4- Aplicar consultas booleanas

In [41]:
import numpy as np

def indice_palabra(word, vocabulario):
    return list(vocabulario).index(word)

def M(word, vocabulario):
    columna = np.zeros((len(vocabulario)), dtype=int)
    columna[indice_palabra(word, vocabulario)] = 1
    return columna

def AND(A, B):
    return np.logical_and(A, B).astype(int)

if "frodo" in vocabulario:
    Query1 = AND(M("anillo", vocabulario), M("frodo", vocabulario))
    print("anillo AND frodo: ", Query1)
else:
    print("Word 'frodo' is not in the vocabulary.")


Word 'frodo' is not in the vocabulary.


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=b824a2a4-ec75-4e0c-9c8d-ae3f8e552746' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>